apiVersion: v1
kind: Service
metadata:
  name: portfolio-api-service
  namespace: portfolio
spec:
  selector:
    app: portfolio-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: portfolio
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379