version: "3.9"

services:

  portfolio-devcontainer:
    build:
      context: .
      args:
        VARIANT: 1.17
        NODE_VERSION: 14
    command: "/bin/bash"
    stdin_open: true
    tty: true
    env_file: portfolio.env
    volumes: 
      - "${PWD}:/workspace"
    networks:
      - internal

  portfolio-cache:
    image: docker.io/redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - internal

networks:
  internal: