apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-api
  namespace: portfolio
  labels:
    app: portfolio-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-api
  template:
    metadata:
      labels:
        app: portfolio-api
    spec:
      containers:
      - name: portfolio-api-service
        image: ghcr.io/angusgyoung/portfolio-api:imageTag
        env:
        - name: GIN_MODE
          value: "release"
        - name: GITHUB_API_URL
          value: "https://api.github.com/graphql"
        - name: CACHE_URL
          value: "redis-service.portfolio:6379"
        - name: CACHE_TTL
          value: "3600"
        - name: CACHE_TIMEOUT
          value: "2"
        - name: CORS_ALLOW_ORIGIN
          value: "https://angus.dotwave.io"
        - name: GITHUB_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-api-token
              key: token
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/v1/pf/ping
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: 50m
      imagePullSecrets:
      - name: ghcr