apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-client
  namespace: portfolio
  labels:
    app: portfolio-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-client
  template:
    metadata:
      labels:
        app: portfolio-client
    spec:
      containers:
      - name: portfolio-client
        image: ghcr.io/angusgyoung/portfolio-client:imageTag
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
      imagePullSecrets:
      - name: ghcr
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: portfolio-client-hpa
  namespace: portfolio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: portfolio-client
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-client-service
  namespace: portfolio
spec:
  selector:
    app: portfolio-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80