apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-api
  namespace: portfolio
  labels:
    app: portfolio-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-api
  template:
    metadata:
      labels:
        app: portfolio-api
    spec:
      containers:
      - name: portfolio-api-service
        image: ghcr.io/angusgyoung/portfolio-service:imageTag
        env:
        - name: GITHUB_API_URL
          value: "https://api.github.com/graphql"
        - name: CACHE_TTL
          value: "120"
        - name: CACHE_TIMEOUT
          value: "2"
        - name: GITHUB_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-api-token
              key: token
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
      imagePullSecrets:
      - name: ghcr
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: portfolio-api-hpa
  namespace: portfolio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-api-service
  namespace: portfolio
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080