# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Update base resources

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'k8s/base/**'

env:
  K8S_CLUSTER: k8s-1-21-3-do-0-lon1-1634243075945

jobs:
  update-base-resources:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Save kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.K8S_CLUSTER }}
      
      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -k $GITHUB_WORKSPACE/k8s/base