name: Build and deploy client to Netlify

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'client/**'

jobs:
  build-and-deploy-client:
    name: Publish to Netlify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - uses: actions/setup-node@master
      
      - run: npm install
        working-directory: client

      - run: npm run build
        working-directory: client

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './client/dist'
          comment-on-commit: true